### ISSUE TITLE
How to install this plugin? Are there any installation and use steps?

### ISSUE THREAD

**Issue by zgpnuaa** [aarkue/ckeditor5-diagrams#1]
I run  `npm install ./ckeditor5-diagrams` , An error occurred：
`Error: Cannot find module 'ckeditor5-diagrams/node_modules/ckeditor5/build/ckeditor5-dll.manifest.json'`

**Comment by aarkue** [comment]
Hi, thanks for your interest in this plugin!
Sorry, I did not get around to write install instructions yet. Currently this plugin is not published on npm but can be installed from github directly using `npm i git+https://github.com/aarkue/ckeditor5-diagrams.git`.

Let me know if this does not work for you.


To actually use the plugin you will need to create a custom ckeditor build (see [https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html#building-the-editor-from-source)).
The buttons `insertDiagram` and `editDiagram` can then be added to the UI and are then used to interact with diagrams.

I can also provide an example build project in the next few days if needed.

Cheers


Edit: If you have no working ckeditor customization already, I recommend using the [online builder](https://ckeditor.com/ckeditor-5/online-builder).

**Comment by zgpnuaa** [comment]
Thanks, I'll try again. I'm looking forward to your installation instructions and examples, a demo would be better.

**Comment by aarkue** [comment]
Hey, thanks for sticking around!
I added install instructions, an example editor build (see the editor_build_sample folder), and a live example.
You can find all of the details in the updated README.md.

Cheers

**Comment by zgpnuaa** [comment]
That's cool. It's a great feature.
After learning your instructions, I realized this great function.
Thank you very much.
